### ISSUE TITLE
[Feature Request] Individual control mapping per system?

### ISSUE THREAD

**Issue by kathyrollo** [higan-emu/ares#1268] opened 2023-10-22 04:32 UTC
**Is your feature request related to a problem? Please describe.**
It is quite a frustrating UX when the controller needs to be mapped every time for each system. A single "universal" virtual gamepad config does not fit for different types of controllers.

**Describe the solution you'd like**
Each system saves its own controller mapping into individual INI files - `mappings/mega32x.ini`, `mappings/n64.ini`.

**Describe alternatives you've considered**
A possible workaround is to create a new instance of ares for every system that needs a different mapping. 

**Additional context**
The workaround effectively defeats the purpose of ares as an all-in-one emulator it has now become, compared to its original purpose.

**Comment by FitzRoyX** [comment] 2023-10-23 19:34
This is a duplicate of https://github.com/ares-emulator/ares/issues/173. The idea behind not doing this is:

1) Modern (including pads from Sony, Microsoft, and Nintendo) are pretty standard now with minor differences. They have a dpad on the left, 4 face buttons on the right, 2 middle buttons, and 4 shoulder buttons. Most retro pads all the way back to the NES translate to these pads fairly obviously because they're the same sort of layout but with less buttons. Even 6 button pads translate fairly obviously, with two of the top buttons needing to go to shoulders.
2) The ancient outliers like Colecovision aren't popular enough to influence what we do with other systems. And the mappings are going to be pretty random regardless. Its buttons are a numpad that doesn't even match keyboard numpad. There's nothing to be done except map it to something and learn to use it.

As the number of systems grows, it's a big ask to say "here's an emulator that supports 100 systems, and every single one requires manual setup before you can play it."

I personally think the virtual pad window would be much nicer if it were redesigned as a table where every system's mappings can be seen at once. Using a dropdown box makes it harder to see the virtual pad linkages.

**Comment by Shideravan** [comment] 2023-10-24 01:16
> As the number of systems grows, it's a big ask to say "here's an emulator that supports 100 systems, and every single one requires manual setup before you can play it."

On the contrary, if there were more than 100 systems, it would be **unfeasible**  to continue without an option for individual system setting input too.

Have you seen the number of strange controls that would have to be "pushed" in the global configuration when a number of emulated systems rises? lol
_e.g. Jaguar, Channel F, CDi, Virtual Boy..._

The option of being able to make an individual control settings for any system can coexist peacefully with a global input setting.

Emulators such RetroArch or MAME (that have tens of thousands of systems emulated) already do this and they don’t have any problem making individual settings when necessary.

**Comment by kathyrollo** [comment] 2023-10-24 08:04
> @FitzRoyX 
> As the number of systems grows, it's a big ask to say "here's an emulator that supports 100 systems, and every single one requires manual setup before you can play it."

Individual controller mapping does not mean the removal of the global mapping, but rather an _addition_. In the same way that per-game audio/video config (for example) in other emulators does not remove the global audio/video settings, but rather just overrides global when per-game is present. No need to config 100 games to start playing.

> @Shideravan 
> The option of being able to make an individual control settings for any system can coexist peacefully with a global input setting.

This is very much the proposal. Thank you.

The number of times this request pops up from both end-users and contributors can also be taken into account as reasonable UX feedback. In general, the more an application supports multiple modules, the more it becomes necessary to have _both_ global and individual preferences per module.

RetroArch, MAME, Mednafen, and FBNeo already have this in place, so it's an established standard for multi-system emulators.

Thanks for reading!

**Comment by FitzRoyX** [comment] 2023-11-01 10:34
> Have you seen the number of strange controls that would have to be "pushed" in the global configuration when a number of emulated systems rises? lol _e.g. Jaguar, Channel F, CDi, Virtual Boy..._

These are your examples of strange? The only oddity in any of this is the jaguar's numpad, which is not required by any game and would probably be left unmapped or mapped to the keyboard numpad.

![vb_2](https://github.com/ares-emulator/ares/assets/57089001/63dcacd9-0f6a-4ca9-832c-0eb7ae852a9e)
---
![cdi_2](https://github.com/ares-emulator/ares/assets/57089001/139ca6e2-e6bb-43dd-8cc5-c63fc837983d)
---
![jag2](https://github.com/ares-emulator/ares/assets/57089001/30f70612-5ea5-4300-a796-8a7369a4bdae)

I don't think I need to post 20 systems we already support that follow the same logic, but here's the n64. I fail to see what we're doing wrong or what the better alternative is.

![n64_2](https://github.com/ares-emulator/ares/assets/57089001/c0a210fb-52d7-4f6c-9a19-3eb006b552b4)

**Comment by LukeUsher** [comment] 2023-11-13 23:42
Duplicate of #173

**Closed as completed by LukeUsher** 2023-11-13 23:42 UTC
Labels: duplicate

**Comment by rrrcabral** [comment] 2025-01-08 11:06
I think the emulator should already come with a 'virtual gamepad' already configured. When it detects an Xbox controller, for example, it already configures everything for that controller. There are emulators with this Auto-Mapping.

Because I find it very confusing that Ares changes a button in one system and it automatically changes in another. You have to keep trying to figure out which is the most correct and coherent button between different systems, and there are systems that can be contradictory. That's why the emulator should already come with a default virtual gamepad configured. Since the author sees logic in this unifying buttons between systems, he certainly knows which is the ideal button between different systems. Leaving it up to the user to find out breaks the excuse that this unification exists to "make it easier for the user."
