### ISSUE TITLE
CHD support does not have support for MODE1 track types (possibly others)

### ISSUE THREAD

**Issue by remutro** [higan-emu/ares#984] opened 2023-02-18 13:30 UTC
**Describe the bug**
While compressing Sonic CD from bin/cue to CHD format, it was found the game wouldn't load and kick users back to the music player without explanation. It makes it look like the game itself doesn't work in the emulator. Currently we only have support for _RAW and AUDIO track types built in. 

**To Reproduce**
1. Find a game (check *.cue file) for a game with MODE1 (ex. Sonic CD), or another track type other then _RAW & AUDIO
2. Compress the game using chdman with the createcd command
3. Attempt to load game in ares
4. If the console is available, you will see a message about an unsupported track type.

**Expected behavior**
Game loads and is playable as we claim support for the CHD format

**Comment by LukeUsher** [comment] 2023-02-19 17:42
While a valid issue, the issue is not so much lack of mode1 support, but because the chd was created from an iso (2048 bytes per sector) rather than a bin, meaning it is missing all non-user data from the image. 

This usually only occurs with bad dumps (the games should be dumped with raw reading) or with homebrew/Rom hacks that shipped as iso rather than bin, it should never happen with good rips of legit discs. 

(For reference I have only tested using chd, and I can play sonic cd just fine)

**Comment by TascoDLX** [comment] 2023-02-19 21:04
I don't really agree with that point. ares already has the ability to generate ecc data from 2048-byte user data (via nall::CD::RSPC). But even so, it currently does nothing itself to validate/exercise ecc data. Regarding 2048-byte-sector images: they aren't _necessarily_ invalid, but more work is required to validate them. But again, if ares isn't doing any data-integrity checks on images (or roms, for that matter), I see this as more of a philosophical argument.

**Comment by LukeUsher** [comment] 2023-02-19 22:33
> I don't really agree with that point. ares already has the ability to generate ecc data from 2048-byte user data (via nall::CD::RSPC). But even so, it currently does nothing itself to validate/exercise ecc data. Regarding 2048-byte-sector images: they aren't _necessarily_ invalid, but more work is required to validate them. But again, if ares isn't doing any data-integrity checks on images (or roms, for that matter), I see this as more of a philosophical argument.

I didn’t say that we weren’t going to fix it, just that and discs dumped via recommended/verified means won’t run into this.

**Comment by remutro** [comment] 2023-02-20 01:40
I may be slightly confused here, but when I tested converting to CHD, Sonic CD was in bin/cue format, and was a redump verified image at the time. No ISO involved. 

If there were previous conversions involved and we can't/won't add support for additional track types, we should at least do something besides printing a message in the console (which isn't available by default in Windows builds) that point to a potential problem because as of now, it looks like ares has an issue playing the actual game, which isn't really accurate and the end user will have no way of knowing it is an issue with the original image/CHD image. So even a message box with more info would be better then silently failing.

**Comment by TascoDLX** [comment] 2023-02-20 03:49
Despite being labelled as BIN, the data track is actually stored as MODE1/2048, conventionally called ISO. You could simply change the file extension to ISO as that would be more familiar. If you have the means, you can convert the track 1 BIN file from MODE1/2048 (ISO) to MODE1/2352 and edit the track type in the CUE to workaround the issue.

**Comment by remutro** [comment] 2023-02-20 16:11
Ah, so it was already converted prior. Gotcha.

**Comment by LukeUsher** [comment] 2023-02-20 19:33
Support for Mode 1 (2048 bytes per sector) is fixed as of [a79a9f0](https://github.com/ares-emulator/ares/commit/a79a9f0fbfbd50af241e19625651f42e56bba6b8)

Will deal with other formats as they come up on a case by case basis but I don't expect to ever see them with the current list of supported systems.

**Closed as completed by LukeUsher** 2023-02-20 19:33 UTC
