### ISSUE TITLE
[NES] Rockman (J), and the other versions too. (Bug Confirm)

### ISSUE THREAD

**Issue by felonyf0x** [higan-emu/ares#1255] opened 2023-10-09 19:59 UTC
Game Works fine only on Cutman Stage, in all other Stages the game auto-pause sequencialy, even i set clear to select buttom, Unplayable.

Note: i was think this bug could be because some random drivers i install on Windows 10 but not, even after i format my HDD the related problem continues.

**Comment by FitzRoyX** [comment] 2023-10-17 04:35
This is being caused by the stupid "feature" known as runahead. Turn it off

**Comment by LukeUsher** [comment] 2023-10-17 09:46
Should be fixed as of 401df969b09a33d9474e2844bd5e982c1a881097

Save states for the NES were not including some controller state; leading to chance that loading a save-state could cause phantom button presses; as runahead relies on save states, that explains the issue.

**Closed as completed** 2023-10-17 09:50 UTC
