### ISSUE TITLE
[MEGADRIVE] Black screen at the start - Triple Play - Gold Edition (USA)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#682] opened 2022-08-22 11:44 UTC
Emulator : Ares 1.29
Nightly build 2022-08-20 21:03:27 UTC
Options : Default
Game : Triple Play - Gold Edition (USA)
System : Megadrive / Genesis

Black screen at the start. No Sega logo.

**Comment by LukeUsher** [comment] 2022-08-22 14:20
Duplicate of #242

**Closed as completed by LukeUsher** 2022-08-22 14:20 UTC
Labels: duplicate, core-md
