### ISSUE TITLE
[N64] angrylions cycle-accurate RDP emulation test rom

### ISSUE THREAD

**Issue by jeltaqq** [higan-emu/ares#967] opened 2023-02-11 11:10 UTC
**Describe the bug**
ares nightly 2023-02-10, Extract rar file and run the test ROM [rrhotel13-2.rar](https://sourceforge.net/p/angrylions-stuff/tickets/_discuss/thread/9e3b608a/50b8/attachment/rrhotel13-2.rar), I get many '00'. This seems to be an incorrect timing for RDP emulation.

**Expected behavior**.
Get a graphic that looks like hardware, then strange numbers.

**Screenshots**
ares 
![ares](https://user-images.githubusercontent.com/25340049/218254723-bb96762c-c73e-47e0-b30b-3359baa3bd4d.png)
hardware with ED64
![ed64](https://user-images.githubusercontent.com/25340049/218254730-bb42347d-4836-4e47-842d-dc0849febdf0.png)
![ed64](https://user-images.githubusercontent.com/25340049/218254736-f84cefd1-f9da-45a4-8fd8-f27cf7871841.gif)

**Additional context**
https://sourceforge.net/p/angrylions-stuff/tickets/10/

**Comment by remutro** [comment] 2023-02-11 13:37
ares (by default, if your system supports vulkan), makes use of parallel-rdp which is of course known to not be cycle accurate. There is no expectation that it is. Fortunately this doesn't impact games. I'm sure eventually ares will get its own unique RDP implementation, but if MAME's is any indication (or Angrylion for that matter), no one will be running games at full speed for a while. 

As a fallback (and you can enable if you want in settings > video, disable GPU acceleration), ares relies on MAME's RDP implementation - which has known issues.

Angrylion can't be used due to license incompatibilities.

**Comment by rasky** [comment] 2023-02-13 15:36
This ROM tests what can be thought as an undefined behavior of RDP. Putting the RDP command list through libdragon's rdpq validator shows several potential issues, including the one that the ROM is supposed to test:

```
[0x130809830] fc26a03f1ffc92f8    SET_COMBINE_MODE cyc0=[(tex1-tex0)*lod_frac+tex0, (tex1-tex0)*lod_frac+tex0], cyc1=[(tex0-0)*0+prim, (0-0)*0+comb]
[0x1308098a8] 3602802800000000    FILL_RECT        xy=(0.00,0.00)-(10.00,10.00)
[RDPQ_VALIDATION] ERROR: in 1cycle mode, the color combiner cannot access the COMBINED slot
[RDPQ_VALIDATION]        SET_COMBINE_MODE last sent at 0x130809830
```

that is, the used of the COMBINED slot in 1cycle mode. While I appreciate that a commercial game happens to rely on this, neither mame-RDP nor parallel-RDP implement this correctly. parallel-RDP does explicitly lists this case among the undefined behaviors where it differs from angrylion, as a more accurate implementation would completely kill any GPU parallelism:

https://github.com/Themaister/parallel-rdp#intentional-differences-from-reference-renderer

```
CombinedColor/Alpha in first cycle is cleared to zero. Some games read this in first cycle, 
and reference renderer will read whatever was generated last pixel. This causes issues
in some cases, where cycle accuracy would have caused the feedback to converge to zero over time.
```

Notice that this quote and the linked thread in Angrylion's SF forum talks about "cycle accurate RDP rendering", but the term might be confusing. This is not about correctly emulating the duration of each RDP command (down to perfect accuracy) instead of emulating an infinitely fast RDP like we do now. What they mean is "emulating the internal RDP pipeline", which basically means reproducing the *internal* behavior of the RDP for each clock cycle and how it affects its internal registers. So in a way, that would be an even lower LLE emulation than what we have right now. Doing it that way, would be extremely slow and would make using GPU probably useless, so the outcome would be an emulator that's not usable for realtime interactive usage (aka: you cannot play games on it). 

I think this is outside the scope of Ares at the moment, so I'll close this issue. In any case, we currently don't directly maintain either of our RDP implementations, so if the original poster wants to pursue this further, I suggest to open the issues upstream (to mame and parallel-RDP).

**Closed as completed by rasky** 2023-02-13 15:36 UTC

**Comment by jeltaqq** [comment] 2023-02-15 11:29
Thanks for investigating the issue!
