### ISSUE TITLE
[Input] No keyboard or controller support ?

### ISSUE THREAD

**Issue by cocopickle** [higan-emu/ares#299] opened 2021-11-14 16:17 UTC
Ok so i'm stuck on this screen => [https://a.tmp.ninja/geJPDtm.jpg](https://a.tmp.ninja/geJPDtm.jpg)
No input from the keyboard work, no input from my controller work. My controller is a Xbox 360 imitation, it works on other games !

Any idea ?

**Comment by LukeUsher** [comment] 2021-11-14 17:19
Duplicate of #298, this issue has been solved in the latest development builds. 

Please search issues before creating a new one.

**Closed as completed by LukeUsher** 2021-11-14 17:19 UTC
