### ISSUE TITLE
[32X] Black screen at the start with Ecco the Dolphin (USA) (Demo) (Developer Cart)...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#730] opened 2022-09-11 09:26 UTC
Emulator : Ares 1.29
Nightly build 2022-09-10 23:02:19 UTC
Options : Default
Game : Ecco the Dolphin (USA) (Demo) (Developer Cart)
System : 32X

Quick test with picodrive on  RA. You can see the video intro.

**Comment by TascoDLX** [comment] 2022-10-15 08:04
The Ecco 32X rom is built for dev hardware which uses different security code than retail. It requires one of the following:
- 32X devkit bios (which may be hard to track down)
- An alternative bios that omits security code validation (like Devster's replacement bios)
- High-level emulation of the bios (what Picodrive does)
- Implant the retail security code block into the Ecco rom instead

Note, Ares currently does not support user-provided bios files for the 32X. It always uses built-in retail version.

**Comment by LukeUsher** [comment] 2023-10-20 19:25
Closing this as "not a bug" because it doesn't work on real 32X hardware either.

**Closed as completed by LukeUsher** 2023-10-20 19:25 UTC
Labels: invalid, core-md, game-is-prototype
