### ISSUE TITLE
[SNES] CPUMSC reset test - doesn't work [ares-v127]

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#427] opened 2022-03-06 00:03 UTC
> https://github.com/PeterLemon/SNES/blob/master/CPUTest/CPU/MSC/CPUMSC.sfc
> 
> This rom has a test for the snes reset feature which does not work, instead of resetting the system and showing that the test has passed it will get stuck displaying garbage graphics.
> 
> It works on the sd2snes, has been reported as working in bsnes sometime in the past and it still works in the mednafen bsnes fork.
> 
> **[...]**
> 
> Its fixed in the jgemu bsnes fork.
> 
> https://gitlab.com/jgemu/bsnes/-/commit/3227e0102f1453b8ff2e9217c7a826d7fb38874a

Source: https://github.com/bsnes-emu/bsnes/issues/235

**Comment by remutro** [comment] 2022-12-31 02:37
@Max833 - What are the expected results of this test? Do you have a screenshot? 

I tried using the latest version of BSNES, and after loading the ROM and choosing the reset option as instructed it just gives a solid blue screen. 

Same result in Ares. The code is very much the same here in Ares still, and applying the changes that were made in jgemu's fork results in getting a green screen after resetting, instead of blue. Does green mean good/pass?

**Comment by orbea** [comment] 2023-01-02 15:56
This is the pass screen as shown in bsnes-jg.
![cpumsc](https://user-images.githubusercontent.com/4204285/210254442-b7847574-5ee0-4bcd-af70-357dd17af5ae.png)

**Comment by remutro** [comment] 2023-01-02 17:28
Thanks. Applying the same changes does allow the test to pass....eventually. But there seems to be another difference here. The colors end up changing, and depending on the what colors are in use you may not see any results. But resetting keeps rotating through colors and eventually you can see the results. So there is something else interfering with this test.

Also worth noting that nothing will display after resetting without "pixel accuracy" being used (black screen using scanline renderer).

![cpu](https://user-images.githubusercontent.com/84990500/210263110-b46aef22-b895-4f53-96ee-2644a2fb3aa0.png)

**Comment by orbea** [comment] 2023-01-02 17:54
The bsnes-jg fork only has the accurate ppu. I would guess something is being reset that should not be, I had very similar nondeterministic results when troubleshooting the patch for the jg fork.

**Comment by remutro** [comment] 2023-01-03 03:24
@orbea @Max833
Aha! Found the color changing issue. Should also not be randomizing CGRAM either when reset, along with the other !reset checks needed:

``` 
if(!reset) {
   random.array({cgram, sizeof(cgram)});
   for(auto& word : cgram) word &= 0x7fff;
} 
```

Why doesn't this seem to impact bsnes/jgemu's fork? Because this randomization of cgram was handled in PPU::Screen::power()  (in ppu.cpp), and there is already an if(!reset) check prior to calling screen->power(), so this code never executes. However in Ares, the cgram randomization happens directly in PPU::power(bool reset)

I have a branch with all changes including fixes for both with and without "pixel accuracy". Would be great though to get some confirmation that this sounds correct. I haven't been able to identify any side effects myself.

**Comment by orbea** [comment] 2023-01-03 15:16
I'm far from an expert and I am not sure there is hardware confirmation of the behavior yet, but if it works then its probably fine.

**Comment by remutro** [comment] 2023-01-03 19:50
Unfortunately that isn't good enough for this project. It needs to be accurate to hardware in order to be accepted (or at least in line with what everyone believes is the correct behavior).

**Comment by carmiker** [comment] 2023-01-04 14:17
This was tested on real SNES hardware by the author of the test, and the bsnes-jg behaviour is consistent with this. Additionally, I can confirm it works as expected on the Super Nt.

**Comment by remutro** [comment] 2023-03-24 23:35
Fixed with pull request: https://github.com/ares-emulator/ares/pull/928

Issue can be closed.

**Closed as completed** 2023-03-25 11:47 UTC
Labels: core-sfc
