### ISSUE TITLE
[Feature request] Saving controller profiles / game

### ISSUE THREAD

**Issue by nan0tEch** [higan-emu/ares#1281] opened 2023-11-08 21:06 UTC
On the N64 Goldeneye i'm glad i can use my PS Dualsense Wireless Controller to setup the 2 analog sticks for 2 different N64 controllers. If i want to play Mario kart 64 i need to change the whole controller setup. 

Lets setup the default controller for all games and if you want a different setup for a game you can do that and save it for that game and auto load that profile when the game starts.

**Comment by FitzRoyX** [comment] 2023-11-09 23:17
> If i want to play Mario kart 64 i need to change the whole controller setup.

Why? That game basically only uses two C buttons for trivial map and camera toggles. You can't use the R-Stick for that?

**Comment by LukeUsher** [comment] 2023-11-13 23:42
Possible duplicate of #173, and #1268

Those issues specify "per system", but per-game could fall under the same umbrella.

**Closed as completed by LukeUsher** 2023-11-13 23:42 UTC
Labels: duplicate
