### ISSUE TITLE
clone cd images file total support for cd based system

### ISSUE THREAD

**Issue by anonyme-x22** [higan-emu/ares#883] opened 2022-11-28 01:57 UTC
**Is your feature request related to a problem? Please describe.**
Img file from clone cd are already supported but need a cue to work

**Describe the solution you'd like**
Directly open a ccd instead of making a cue for it.

**Describe alternatives you've considered**
Make a cue for the img file

**Additional context**

**Comment by LukeUsher** [comment] 2022-11-28 09:08
Please don't create duplicate issues

Duplicate of #882

**Closed as not planned by LukeUsher** 2022-11-28 09:08 UTC
Labels: duplicate
