### ISSUE TITLE
[N64] macOS impossible to playing

### ISSUE THREAD

**Issue by naymapl** [higan-emu/ares#452] opened 2022-03-12 12:06 UTC
https://www.youtube.com/watch?v=ZGKnNAGNxVg

Here is movie how run on many games. I have problem with lagging, sound issue, input issue in some games. The worse is this lagging. I using openEMU who use mupen64plus for n64 emulation and there is no issue at all with graphic or sound.

**Comment by rasky** [comment] 2022-03-12 13:29
@naymapl can you try a game of another system emulated by Ares, to check whether the problem is specific of the N64 emulation?

**Comment by remutro** [comment] 2022-03-12 16:19
This game plays at a smooth 60 fps when using parallel-rdp on my (Windows) system. But if I switch to using MAME RDP  (which is the only option for macOS) then I can't keep a consistent framerate. It bounces around between 35 - 50 fps during the intro sequence just like the video posted. Since it isn't running at full speed, audio distortion and input lag is to be expected. 

I also tried the PAL version, where full speed is 50 fps. This was much closer to playable then the NTSC-U version. You might want to try the PAL release and see if you get better performance.

**Comment by naymapl** [comment] 2022-03-12 16:19
I checked PSX with few bioses and have no screen on grand turismo 2 arcade.
This is strange. With Duckstation working well.

**Comment by remutro** [comment] 2022-03-12 16:21
Playstation is an extremely early core and hasn't received much attention yet. We are working on compatibility lists here (note that all games for all systems haven't been tested yet):
https://ares-emu.net/compatibility

**Comment by LukeUsher** [comment] 2022-03-14 09:33
Yeah I'm going to close this; it's not so much a bug as it is your CPU not being able to keep up with emulating the n64 fully on the cpu.

**Closed as completed by LukeUsher** 2022-03-14 09:33 UTC
Labels: invalid

**Comment by CasualPokePlayer** [comment] 2022-03-14 19:24
In fairness even with an extremely powerful CPU you can't run at full speed with MAME RDP. You'd either need to abuse multithreading ala Angrylion-Plus (which you'd still need a fairly good CPU with many cores), have accuracy tradeoffs (???), or just outright HLE the thing (at which point you aren't really a software renderer).
