### ISSUE TITLE
7Zip support

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#773] opened 2022-09-18 10:10 UTC
**Is your feature request related to a problem? Please describe.**
My megadrive set is in 7zip and I have to unzip the rom to use on Ares

**Describe the solution you'd like**
Support of 7zip to drag and drop my game on ares

**Describe alternatives you've considered**
none idea`

**Additional context**
nothing

**Comment by LukeUsher** [comment] 2022-09-18 11:32
Duplicate of #388

**Closed as not planned by LukeUsher** 2022-09-18 11:32 UTC
Labels: duplicate, enhancement
