### ISSUE TITLE
[N64] Jet Force Gemini

### ISSUE THREAD

**Issue by Alexn64gamer0712** [higan-emu/ares#1107] opened 2023-05-07 09:35 UTC
Jet Force Gemini hangs in intro with this screen with this screen on ares v131
![image](https://user-images.githubusercontent.com/100775660/236669551-9180fe52-ea11-4886-919f-78459701c8bd.png)

Rom info: Jet Force Gemini(U)
cic: CIC-NUS-6105

**Comment by LukeUsher** [comment] 2023-05-07 10:58
Duplicate of #129 ?

**Comment by Alexn64gamer0712** [comment] 2023-05-07 22:27
The gfx numbers are different, dont know if that has something to do btw...

**Comment by kev4cards** [comment] 2023-05-11 21:48
I can confirm this is a duplicate.

Those some gfx numbers are posted in a later comment. That said, the numbers do change upon every commit related to N64 emulation. That's just the nature of the issue.

**Closed as not planned** 2023-05-12 15:39 UTC
Labels: bug, duplicate
