### ISSUE TITLE
[PC ENGINE CD] Atlas, The - Renaissance Voyager (Japan) - Game freeze on the map screen

### ISSUE THREAD

**Issue by Yotamtamtam** [higan-emu/ares#468] opened 2022-03-19 08:46 UTC
Emulator : Ares v126 Nightly Built 26-02-2022
Options : Default
Game : Atlas, The - Renaissance Voyager (Japan)
Core : PC Engine CD
Bios: Version 3.00

Game freeze on the map screen

![Atlas_01](https://user-images.githubusercontent.com/87193210/159114365-3faba110-5fbc-4a74-a944-5a525060853e.png)

**Comment by ToastmanJack** [comment] 2023-04-23 07:52
Just tested it out on v132 and the same screen popped up but its just to indicate that the game is loading, if you wait a while, you can load in the game and it seems to work as intended, we can probably close this.

**Comment by LukeUsher** [comment] 2023-04-23 09:21
![A4815615-60EC-4B9A-80D7-6B922BDA24E9](https://user-images.githubusercontent.com/740003/233831068-4b8f2048-b09f-46bd-8eb7-9541c0c5af10.jpeg)

Google Translate confirms this is just a loading screen; please consider running such screens through a translation engine before creating an issue, as this will help to avoid erroneous reports.

**Closed as completed** 2023-04-23 09:21 UTC
Labels: core-pce
