### ISSUE TITLE
The Input tab of the Configuration window is wonky on Windows

### ISSUE THREAD

**Issue by LOuroboros** [higan-emu/ares#419] opened 2022-03-04 15:01 UTC
Title. The only thing I did was to download the latest version of Ares, that is the v127, then I loaded a GBA BIOS and GBA ROM, before going on to configure the controls from the program's GUI.
![%pn_04032022_1158527](https://user-images.githubusercontent.com/4485172/156786764-f4f49a53-50fe-4488-9799-a196761debc3.gif)

**Comment by Max833** [comment] 2022-03-04 16:19
Same with the emulators window: 

![image](https://user-images.githubusercontent.com/53529402/156799979-9c72b849-bf8b-4b5f-b7d0-2b1efa898a62.png)

**Comment by LukeUsher** [comment] 2022-03-04 16:26
Duplicate of #102

**Closed as completed** 2022-03-04 16:26 UTC
Labels: duplicate
