### ISSUE TITLE
v125.1 won't boot games until any dialog is opened/closed.

### ISSUE THREAD

**Issue by Cereal-Killa** [higan-emu/ares#303] opened 2021-11-18 13:43 UTC
Confirmed here on my machine that up to v125 games will load and display graphics pretty much right away.
On v125.1 loading a game remains on a black screen and there will be no graphics until I open just about any setting dialog from the menu and simply close it, no need to change anything on the dialog, then the emulation starts.

v125.1
https://user-images.githubusercontent.com/25939765/142423289-661e8ae0-282c-4f1e-9e9d-3dd5f5cd2b0f.mp4

v125 downwards:
https://user-images.githubusercontent.com/25939765/142423491-354bb66d-f5a5-4c10-9793-c0e54afa3037.mp4

Specs: Core i7 11700, RTX 2060 (496.13)

**Comment by LukeUsher** [comment] 2021-11-18 13:51
Duplicate of #292, #298, #299.

This issue has been solved in the latest development builds (as of 12ac1b5)

Please search recent/closed issues before creating a new one.

**Closed as completed by LukeUsher** 2021-11-18 13:51 UTC

**Comment by Cereal-Killa** [comment] 2021-11-18 14:08
Ooops! Sorry man I should have checked the closed issues.
Tks!!
