### ISSUE TITLE
Feature Request: Update Version Using the Menu Bar

### ISSUE THREAD

**Issue by Cicero357** [higan-emu/ares#1503] opened 2024-05-18 02:23 UTC
**Is your feature request related to a problem? Please describe.**
No, this request is not related to a problem. 

**Describe the solution you'd like**
Add a feature that enables the user to update to the latest version of Ares using in the menu bar. 

**Describe alternatives you've considered**
Even though manual updating works great, adding the ability to update using the GUI would be great for a wide set of users. This includes people who are not super tech savvy to those that would like to update as quickly as possible, just to name a few, 

**Additional context**
This would be a great feature to have! I have provided a screen shot that shows how Rosalie's Mupen GUI (V0.5.9) implements the update feature in the menu bar. 

![RMG v0 5 9](https://github.com/ares-emulator/ares/assets/63135347/c6465790-fb05-4cd4-834b-7313f30e66b8)

**Comment by LukeUsher** [comment] 2024-06-10 07:28
Very similar/possible duplicate of #236

**Closed as completed by LukeUsher** 2024-06-10 07:28 UTC
Labels: duplicate
