### ISSUE TITLE
[MEGADRIVE] Freeze on the press start screen - Wonder Boy V - Monster World III (USA, Europe) ... 

### ISSUE THREAD

**Issue by BenjaminSiskoo** [higan-emu/ares#680] opened 2022-08-22 08:35 UTC
Emulator : Ares 1.29
Nightly build 2022-08-20 21:03:27 UTC
Options : Default
Game : Wonder Boy V - Monster World III (Japan, Korea), Wonder Boy in Monster World (USA, Europe)
System : Megadrive / Genesis

Freeze on the press start screen. the game works with : Wonder Boy V - Monster World III (Japan, Korea) (Beta) (1991-07-25).

**Comment by TascoDLX** [comment] 2022-09-26 04:10
Freeze after pressing start likely means eeprom failure caused by incorrect header (misidentified as sram). The UE version is already fixed up in Mia, but the J version needs to be added w/ same params as UE.

Wonder Boy in Monster World (USA, Europe)
6b2ac36f624f914ad26e32baa87d1253aea9dcfc13d2a5842ecdd2bd4a7a43b9

Wonder Boy V - Monster World III (Japan, Korea)
d758864efa18da7a8a87dce32a5b61a8067fb60846696a9588956bc316e480f9

**Comment by Shideravan** [comment] 2022-09-29 00:32
Fixed in #800 
![image](https://user-images.githubusercontent.com/12163923/192912091-b3974524-d946-4bd5-839f-d65b9e262777.png)
![image](https://user-images.githubusercontent.com/12163923/192912147-5133758c-22d5-40b4-b739-59b5977c6292.png)

**Closed as completed** 2022-09-29 08:09 UTC
Labels: core-md
