### ISSUE TITLE
Controller Settings UI Bug

### ISSUE THREAD

**Issue by RayleeZ817** [higan-emu/ares#1407] opened 2024-02-25 15:09 UTC
The UI for this window occasionally break.

Controller Settings:
![image](https://github.com/ares-emulator/ares/assets/104574250/793483ce-6c70-43a0-ae0a-19e401130cd2)

OS: Windows 10
GPU: AMD RX6700XT 
Ares Version: 136 Official

**Comment by Yotamtamtam** [comment] 2024-02-25 17:58
Duplicate of #102

**Closed as completed** 2024-02-25 20:03 UTC
Labels: duplicate
