### ISSUE TITLE
[Nintendo 64] Donkey Kong 64

### ISSUE THREAD

**Issue by Alexn64gamer0712** [higan-emu/ares#962] opened 2023-02-06 13:48 UTC
Before submitting an issue, please use the search to make sure an issue doesn't already exist, you should also make sure your rom is not a bad dump, by comparing against the hashes in the No-Intro (Cartridges) or Redump (CD-ROM) databases.

The game is not booting at all.

**Rom Information**
name:     Donkey Kong 64 (USA)
  title:    Donkey Kong 64 (USA)
  region:   NTSC
  id:       NDOE
  rumble
  revision: 1.0
  board
    cic: CIC-NUS-6105
    memory
      type: ROM
      size: 0x2000000
      content: Program
    memory
      type: EEPROM
      size: 0x800
      content: Save

![image](https://user-images.githubusercontent.com/100775660/216988000-aab602ef-bd95-430b-b5cd-f10b318a4826.png)

**Comment by asiekierka** [comment] 2023-02-06 14:24
Duplicate of https://github.com/ares-emulator/ares/issues/605

**Comment by Alexn64gamer0712** [comment] 2023-02-06 20:09
Im really sorry, I wasnt aware of being a duplicate, can you merge them please? and btw, do you know if there will be a fix for DK64? for it to be fully functional (no graphic glitches, etc), thank you in advance

**Comment by remutro** [comment] 2023-02-06 22:35
Eventually yes. It comes down to timing and unknown parts of the system. A number of folks are working on figuring out what correct timings are. It can be forced to work by altering the timings to get the game to run, but that is a hack. And ares is focused on accurate preservation of the hardware, so no per-game hacks.

I should also point out there is a compatibility database: https://ares-emu.net/compatibility/15
It is usually up-to-date, but usually not in-between releases as things change if you are pulling nightly builds. And the N64 core is one of the cores receiving the most attention currently.

**Comment by Alexn64gamer0712** [comment] 2023-02-06 22:52
I really like and support the way you are focusing emulation, I always priorize accuracy and preservation over just being able to play the game, it is ok if I have to wait for months, dont worry, I prefer playing the game on almost full accuracy rather tan playing and constanlty having glitches of some sort, good things are worth waiting, Ill check the compatibility database next time before posting, thanks a lot

**Comment by rasky** [comment] 2023-02-13 15:41
Duplicate of #605

**Closed as not planned by rasky** 2023-02-13 15:41 UTC
Labels: bug, duplicate
